"""fix alert metadata column name

Revision ID: 7c98f5265943
Revises: fb57f60ff3f9
Create Date: 2026-01-19 00:22:28.322004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c98f5265943'
down_revision: Union[str, None] = 'fb57f60ff3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('alert_metadata', sa.JSON(), nullable=True))
    op.add_column('alerts', sa.Column('resolved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.drop_column('alerts', 'is_resolved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_resolved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_column('alerts', 'resolved')
    op.drop_column('alerts', 'alert_metadata')
    op.drop_column('alerts', 'entity_id')
    op.drop_column('alerts', 'entity_type')
    # ### end Alembic commands ###
