"""initial schema

Revision ID: fb57f60ff3f9
Revises: 974ccb5264fb
Create Date: 2026-01-12 22:53:26.053793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb57f60ff3f9'
down_revision: Union[str, None] = '974ccb5264fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecasts_id', table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('forecast_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('forecast_horizon', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predicted_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lower_bound', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upper_bound', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('training_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='forecasts_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='forecasts_pkey')
    )
    op.create_index('ix_forecasts_id', 'forecasts', ['id'], unique=False)
    # ### end Alembic commands ###
